### ISSUE TITLE
why there is no resonse for the command?

### ISSUE THREAD

**Issue by zhang8083** [arcreative/homebridge-xbox-one#5]
my xbox-one OS version is 10.0.14393.1065
i'm sure the ip address & live id are correct in the config file
but there is no response for the command i send in homebridge

"
[11/2/2016, 3:14:53 PM] Homebridge is running on port 51826.
[11/2/2016, 3:14:56 PM] [Xbox] Sending on command to 'Xbox'...
[11/2/2016, 3:14:58 PM] [Xbox] Sending on command to 'Xbox'...
...
"

the following  is my configuration
"accessories": [{
  "accessory": "Xbox",
  "name": "Xbox",
  "ipAddress": "192.168.77.193",
  "liveId": "FD00BDB6AD6137FD"
}
]

**Comment by arcreative** [comment]
Is your Xbox set to instant on mode?  You also might want to set a static IP so your Xbox doesn't bounce around and stop working.

**Comment by zhang8083** [comment]
@arcreative  yes, i set  static dhcp mode in router, the ip address is stable.
and how to set instant on mode?  Even though,the xbox is poweron state, i could not powroff it via command.

**Comment by arcreative** [comment]
Unfortunately, we can't turn it off at present due to the inability to access the proprietary control APIs. Instant on mode is set via the Xbox one power settings--it's the same setting that lets you wake it up with Kinect.

**Comment by arcreative** [comment]
@zhang8083 Closing this, as I don't think there's anything to be done here.  If you were originally wondering about confirmation of the Xbox turning on, we're a bit limited here since the power on packet is a UDP dgram, and we don't really get a response or acknowledgement that the xbox received it.  The best we can do is send a few packets and let homebridge check the power status via ping.
